name: Security

on:
  workflow_run:
    workflows: [ "Deploy" ]
    types:
      - completed
  schedule:
    - cron: '0 6 * * *'

env:
  LATEST_IMAGE: ${{ github.event.repository.name }}:latest

permissions:
  contents: read

jobs:
  vulnerability-analyze:
    permissions:
      contents: "read"
      id-token: "write"
      security-events: write
    name: Security analyze
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: github/codeql-action/init@e675ced7a7522a761fc9c8eb26682c8b27c42b2b # v3.24.1
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/autobuild@e675ced7a7522a761fc9c8eb26682c8b27c42b2b # v3.24.1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@e675ced7a7522a761fc9c8eb26682c8b27c42b2b # v3.24.1
        with:
          category: "/language:${{matrix.language}}"

      - name: Login to Google Artifact Registry
        uses: nais/login@557ec71a21c53ce9a8f672e1889997d2d564bd8c # v0.0.7
        id: login
        with:
          team: okonomi
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

      - name: Run Trivy vulnerability scanner on docker image
        uses: aquasecurity/trivy-action@84384bd6e777ef152729993b8145ea352e9dd3ef # master
        with:
          image-ref: ${{ steps.login.outputs.registry }}/${{ env.LATEST_IMAGE }}
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@e675ced7a7522a761fc9c8eb26682c8b27c42b2b # v3.24.1
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'